### ISSUE TITLE
Spec

### ISSUE THREAD

**Issue by shavymittelman** [shavymittelman/RaceIt#1]

**Comment by shavymittelman** [comment]
HI,
my spec is in my repo
thanks!

**Comment by AshiraFriedman** [comment]
Sounds like a great game, looking forward!
You can move ahead with the wireframe and then code implementation.

**Comment by AshiraFriedman** [comment]
Nice job on the spec!
Please implement the following instruction from the HW PDF "make a “nice” read me that has an overview and picture of game"
Let me know when your wireframe is ready
