### ISSUE TITLE
Code Implementation

### ISSUE THREAD

**Issue by shavymittelman** [shavymittelman/RaceIt#3]

**Comment by AshiraFriedman** [comment]
Great game!  Really nice work!
For the symbols, are they supposed to happen whenever the player pass that box, or only if it's the box that the player's turn ends with?

**Comment by shavymittelman** [comment]
Only if it's the box that the player's turn ends with.

**Comment by AshiraFriedman** [comment]
thanks for clarifying.
Wow!  Amazing job!!
I did QA and a code review, please see 2 small comments but the code was written really nicely!
One bug which you should prevent - if the down arrow is on the last card in the game, it's impossible for that player to ever win, it won't let them get past it.  Please fix that and resubmit

**Comment by shavymittelman** [comment]
Hi,
Now that I'm up to implementing this game with OOP, I realized that I never finished it off completely...
I guess it's never too late:)

**Comment by AshiraFriedman** [comment]
for sure
Great job!  Very nice work!
It didn't let me to push to the repo, you can just remove my old comments from your code.
